{
 "title": "MongoDB",
 "description": "Note for a official Grafana MongoDB plugin, please view:\nhttps://grafana.com/grafana/plugins/grafana-mongodb-datasource\n\nThis is a MongoDB Prometheus Exporter Dashboard. \nWorks well with https://github.com/dcu/mongodb_exporter\n\nIf you have the node_exporter running on the mongo instance, you will also get some useful alert panels related to disk io and cpu.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": "label_values(mongodb_connections, instance)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Query Metrics for $env",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "env",
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_opcounters[5m])) by (legacy_op_type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_opcounters{legacy_op_type=~\"insert|query|update|delete\"}[5m])) by (legacy_op_type)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"query\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Replica Set Metrics for $env",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "env",
   "targets": [
    {}
   ]
  },
  {
   "title": "Member Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(mongodb_rs_members_health)",
     "legendFormat": "# members"
    },
    {
     "expr": "sum(mongodb_replset_member_health{instance=~\"$env\"})",
     "legendFormat": "healthy members"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "graph",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "mongodb_rs_members_health", "legendFormat": "{{state}} - {{name}}" }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcountersRepl[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Health metrics for $env",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "env",
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_ss_uptime" }
   ]
  },
  {
   "title": "Available Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"available\"}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_connections{conn_type=\"totalCreated\"}[5m])"
    }
   ]
  },
  {
   "title": "Resource Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Oplog Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "mongodb_oplog_stats_size", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_wt_connection_memory_re_allocations[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_repl_network_bytes[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Oplog Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    { "expr": "mongodb_oplog_stats_size", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{device=\"nvme0n1\"}[5m]) * 100",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Reads Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"nvme0n1\"}[5m])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Writes Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{device=\"nvme0n1\"}[5m])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  }
 ]
}