apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-kpw
spec:
  acme:
    email: settawuts17@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-kpw
    solvers:
    - http01:
        ingress:
          class: nginx

