apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.kpwApp.name }}-ingress"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_pass http://kpc-candidate-test.s3-website-ap-southeast-1.amazonaws.com;
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:

      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.kpwApp.name }}
            port:
              number: {{ .Values.kpwApp.port }}

      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.kpwApp.name }}
            port:
              number: {{ .Values.kpwApp.port }}