apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.kpwApp.name }}-ingress"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:

      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.kpwApp.name }}
            port:
              number: {{ .Values.kpwApp.port }}

      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: s3-hello
            port:
              number: {{ .Values.kpwApp.port }}