apiVersion: v1
kind: Service
metadata:
  name: kpw-app
spec:
  type: ClusterIP 
  selector:
    app: kpw-app
  ports:
    - port: 80
      targetPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: s3-proxy
spec:
  selector:
    app: s3-proxy
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: kpw-mongo
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      name: mongo
  clusterIP: None
  selector:
    app: mongo

