apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kpwApp.name }}
  namespace: {{ .Values.kpwApp.namespace }}
spec:
  type: ClusterIP 
  selector:
    app: {{ .Values.kpwApp.name }}
  ports:
    - port: {{ .Values.kpwApp.port }}
      targetPort: 80