apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpw-app
spec:
  replicas: kpw-app
  selector:
    matchLabels:
      app: kpw-app
  template:
    metadata:
      labels:
        app: kpw-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources: 
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: kpw-app-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: kpw-app-config
          configMap:
            name: kpw-app-config