apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  namespace: kpw-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
      - name: mongodb-exporter
        image: percona/mongodb_exporter:0.11.2
        ports:
        - containerPort: 9216
        env:
        - name: MONGODB_URI
          value: "mongodb://exporter:exporter@mongo-1.mongo.kpw-mongo.svc.cluster.local:27017/?replicaSet=rs0&authSource=admin"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi