apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-proxy
  namespace: kpw-app-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-proxy
  template:
    metadata:
      labels:
        app: s3-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          
      volumes:
      - name: config
        configMap:
          name: s3-proxy-config