# kpwApp:
#   name: nginx-website
#   namespace: website

#   replicaCount: 1

#   image: nginx:latest
#   pullPolicy: IfNotPresent

#   service:
#     port: 80

#   ingress:
#     className: public
#     host: yourdomain.com