name: Deploy Kubernetes via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Detect changed k8s yaml
        id: changes
        run: |
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep '^templates/' \
            | grep -E '\.ya?ml$' \
            | tr '\n' ' ')
        
            echo "Changed files: $CHANGED_FILES"
            echo "files=$CHANGED_FILES" >> $GITHUB_OUTPUT
            
      - name: Deploy changed YAML to Kubernetes
        if: steps.changes.outputs.files != ''
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/kpw-helm

            echo "Pull latest code" 
            git pull origin main

            echo "Apply namespace first"
            kubectl apply -f templates/namespace.yaml

            echo "Deploy all manifests" 
            kubectl apply -f templates/